### ISSUE TITLE
If user doesn't accept cookie use policy, service Login results in error

### ISSUE THREAD

**Issue by joerob-msft** [navzam/token-store-multi-service-sample#21]
If the user does not accept the "Use this space to summarize your privacy and cookie use policy. Learn More." banner on the main page, logging into either of the services results in an Error page.

> Error.
> An error occurred while processing your request.
> Request ID: 8000001c-0000-e900-b63f-84710c7967bb
> 
> Development Mode
> Swapping to the Development environment displays detailed information about the error that occurred.
> 
> The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

Proposed solution: Detect whether the user has accepted, and don't let them connect accounts until they accept

**Comment by navzam** [comment]
Since we're using the session for essential functionality (phishing mitigation) and not tracking, I instead [marked the session cookie as "essential"](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2#essential-cookies) so that it functions without the user accepting the policy.

The issue would be if someone builds on the sample and adds non-essential session tracking. I added a warning to the README about this.
